#define PORT     8080 
#define MAXLINE 1024 
#define PART_SIZE 1024
#define N_ATTEMPTS 5
#define GET "get"
#define PUT "put"
#define DELETE "delete"
#define LS "ls"
#define EXIT "exit"
#define TIMEOUT 2